name: pynapple
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - bottleneck=1.3.2=py38heb32a55_1
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.10.0=py38h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - hdmf=3.1.1=pyh6c4a22f_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.10.0=py38h578d9bd_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython=7.29.0=py38hb070fc8_0
  - jedi=0.18.0=py38h06a4308_1
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - kiwisolver=1.3.1=py38h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libllvm11=11.1.0=h3826bc1_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - llvmlite=0.37.0=py38h295c915_1
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - matplotlib=3.5.0=py38h06a4308_0
  - matplotlib-base=3.5.0=py38h3ed280b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nose=1.3.7=pyhd3eb1b0_1006
  - numba=0.54.1=py38h51133e4_0
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.0=py38h295c915_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py38h5aabda8_0
  - pip=21.2.4=py38h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pynwb=2.0.0=py38h578d9bd_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pytables=3.6.1=py38h9fd0a39_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - ruamel.yaml=0.16.5=py38h516909a_1
  - ruamel.yaml.clib=0.2.2=py38h7b6447c_0
  - scipy=1.7.1=py38h292c36d_2
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=hc218d9a_0
  - tabulate=0.8.9=py38h06a4308_0
  - tbb=2021.4.0=hd09550d_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - pycircstat==0.0.2
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
