name: pynapple
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - blosc=1.21.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - expat=2.4.1
  - flake8=3.9.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - hdmf=3.1.1
  - icu=58.2
  - importlib-metadata=4.10.0
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - llvmlite=0.37.0
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=2.0.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - munkres=1.1.4
  - nbformat=5.1.3
  - ncurses=6.3
  - nose=1.3.7
  - notebook=6.4.6
  - numba=0.54.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycodestyle=2.7.0
  - pycparser=2.21
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pynwb=2.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pytables=3.6.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - ruamel.yaml=0.16.5
  - ruamel.yaml.clib=0.2.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tabulate=0.8.9
  - tbb=2021.4.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - alabaster==0.7.12
    - arrow==1.2.1
    - astroid==2.6.6
    - astunparse==1.6.3
    - atomicwrites==1.4.0
    - autopep8==1.5.7
    - av==8.1.0
    - babel==2.9.1
    - binaryornot==0.4.4
    - black==21.12b0
    - bleach==4.1.0
    - chardet==4.0.0
    - charset-normalizer==2.0.10
    - click==8.0.3
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - cookiecutter==1.7.3
    - cryptography==36.0.1
    - diff-match-patch==20200713
    - docstring-parser==0.13
    - docutils==0.17.1
    - entrypoints==0.3
    - ghp-import==2.0.2
    - idna==3.3
    - imagesize==1.3.0
    - inflection==0.5.1
    - intervaltree==3.1.0
    - isort==5.10.1
    - jeepney==0.7.1
    - jinja2==3.0.3
    - jinja2-time==0.2.0
    - joblib==1.1.0
    - jupyter-client==6.1.12
    - jupytext==1.13.5
    - keyring==23.5.0
    - lazy-object-proxy==1.7.1
    - markdown==3.3.6
    - markdown-it-py==1.1.0
    - mccabe==0.6.1
    - mdit-py-plugins==0.3.0
    - mergedeep==1.3.4
    - mkdocs==1.2.3
    - mkdocs-autorefs==0.3.1
    - mkdocs-jupyter==0.19.0
    - mkdocs-material==8.1.4
    - mkdocs-material-extensions==1.0.3
    - mkdocs-monorepo-plugin==0.5.1
    - mkdocstrings==0.17.0
    - mypy-extensions==0.4.3
    - nbclient==0.5.9
    - nbconvert==6.4.0
    - nest-asyncio==1.5.4
    - numpydoc==1.1.0
    - pandocfilters==1.5.0
    - pathspec==0.9.0
    - pkginfo==1.8.2
    - platformdirs==2.4.1
    - pluggy==1.0.0
    - poyo==0.5.0
    - psutil==5.9.0
    - pycircstat==0.0.2
    - pydocstyle==6.1.1
    - pylint==2.9.6
    - pyls-spyder==0.4.0
    - pymdown-extensions==9.1
    - pyqt5==5.12.3
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyqtwebengine==5.12.1
    - python-lsp-black==1.0.1
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.2.4
    - python-slugify==5.0.2
    - pytkdocs==0.14.0
    - pyxdg==0.27
    - pyyaml==6.0
    - pyyaml-env-tag==0.1
    - qdarkstyle==3.0.2
    - qstylizer==0.2.1
    - qtawesome==1.1.1
    - readme-renderer==32.0
    - requests==2.27.1
    - requests-toolbelt==0.9.1
    - rfc3986==1.5.0
    - rope==0.22.0
    - rtree==0.9.7
    - scikit-learn==1.0.2
    - secretstorage==3.3.1
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - sphinx==4.4.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - spyder==5.1.5
    - spyder-kernels==2.1.3
    - text-unidecode==1.3
    - textdistance==4.2.2
    - threadpoolctl==3.0.0
    - three-merge==0.1.1
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomli==1.2.3
    - tqdm==4.62.3
    - twine==3.7.1
    - typing-extensions==4.0.1
    - ujson==5.1.0
    - urllib3==1.26.7
    - watchdog==2.1.6
    - webencodings==0.5.1
    - wrapt==1.12.1
    - wurlitzer==3.0.2
    - yapf==0.32.0
prefix: /home/guillaume/miniconda3/envs/pynapple
