site_name: pynapple
nav:  
  - Overview: index.md
  - Usage:
    - Tutorials:
      - Quick start: notebooks/pynapple-quick-start.ipynb
      - Core: notebooks/pynapple-core-notebook.ipynb
      - IO: notebooks/pynapple-io-notebook.ipynb
      - Process: notebooks/pynapple-process-notebook.ipynb
    - pynacollada: pynacollada.md
  - Modules:
    - Core:
      - Time Series: core.time_series.md
      - Interval Sets: core.interval_set.md
      - Time Series Group: core.ts_group.md
    - IO:
      - Miscellaneous: io.md
      - Basic IO: io.loader.md
      - Neurosuite: io.neurosuite.md
      - Phy: io.phy.md
      - CNMF-E: io.cnmfe.md
      - Suite2p: io.suite2p.md
    - Process: 
      - Correlograms: process.correlograms.md
      - Tuning curves: process.tuning_curves.md
      - Decoding: process.decoding.md
      - Peri-Stimulus: process.perievent.md
      - Randomization: process.randomize.md
  # - Plugins:
  #   - pynalog: pynalog.md
  #   - pynapplesonfire: pynapplesonfire.md
  - Contributing: CONTRIBUTING.md
  - Authors: AUTHORS.md
  - History: HISTORY.md
theme:
  name: 'material'
  palette:
    primary: 'green'
  # features:
  #   - navigation.tabs
repo_url: https://github.com/pynapple-org/pynapple
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True      
  - search
  - mkdocstrings
